server:
  port: 7000

spring:
  application:
    name: PRODUCT-SERVICE

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://admin:admin@discovery:8761}/eureka
    healthCheck:
      enabled: true